# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "."
tmp_dir = "/tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build main.go && ./main"

# Customize binary.
# This log file places in your tmp_dir.
log = "air_errors.log"
# Watch these filename extensions.
include_ext = ["go", "yaml",".env"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 500 # ms

[log]
# Show log time
time = true
[color]

[misc]
# Delete tmp directory on exit
clean_on_exit = true
