repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.1.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: golangci-lint
    - id: go-unit-tests
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
  - id: gitleaks
